config/routes.rb
Rails.application.routes.draw do

    devise_for :users

    devise_scope :user do
        get '/admin' => 'devise/sessions#new'
        get '/users/sign_out' => 'devise/sessions#destroy'
    end

    root 'universities#index'

    resources :universities do
        member do
            get 'archive'
            get 'unarchive'
        end
        resources :durations, only: [:new, :create, :destroy]
    end

    match '/search', to: 'universities#search', via: 'get'
    match '/downloads', to: 'static_pages#downloads', via: 'get'
    match '/faq', to: 'static_pages#faq', via: 'get'

    resources :countries do
        member do
            get 'universities'
        end
    end

    resources :departments, only: [:show]

end

app/models/country.rb
class Country < ActiveRecord::Base

    has_many :universities

    validates :name, presence: true
end

app/models/department.rb
class Department < ActiveRecord::Base

    has_and_belongs_to_many :universities

    validates :name, presence: true
    validates :universities, presence: true
end

app/models/duration.rb
class Duration < ActiveRecord::Base

    belongs_to :university

    validates :university_id, presence: true
    validates :to_date, presence: true
    validates :from_date, presence: true
    validates :deadline, presence: true

end

app/models/university.rb
class University < ActiveRecord::Base

   has_and_belongs_to_many :departments
   belongs_to :country
   has_many :durations

   validates :name, presence: true
   validates :departments, presence: true

   def self.search(search, designation)
       search_condition = "%" + search + "%"
       where("#{designation} LIKE ?", "%#{search}%")
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

    def index
        @countries = Country.all
    end

    def show
        @country = Country.find(params[:id])
    end

    def new
        @country = Country.new
    end

    def create
        @country = Country.new
        @country.name = params[:country][:name]
        @country.geocode = params[:country][:geocode]

        if @country.save
            flash[:success] = "Successfully created a new country"
            redirect_to root_url
        else
            render 'new'
        end
    end

    def universities
        @country = Country.find(params[:id])
        @universities = University.where("country_id=?",params[:id])
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

    def show
        @department = Department.find(params[:id])
        @universities = Department.includes(:universities).find(@department.id).universities
    end
end

app/controllers/durations_controller.rb
class DurationsController < ApplicationController

    def new
        respond_to do |format|
            format.html {redirect_to @duration}
            format.js
        end
    end

    def create
        @university = University.find(params[:university_id])
        @duration = Duration.new
        @duration.university_id = params[:university_id]
        @duration.from_date = params[:from]
        @duration.to_date = params[:to]
        @duration.deadline = params[:deadline]

        if @duration.save
            respond_to do |format|
                format.html {redirect_to @duration}
                format.js
            end
        end
    end

    def destroy
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def downloads
    end

    def faq
    end

end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController

    def index
        @universities = University.where(archived: 'false').reverse_order
    end

    def show
        @university = University.find(params[:id])
    end

    def new
        @university = University.new
    end

    def create
        @university = University.new
        @university.name = params[:university][:name]
        @university.country_id = params[:university][:country_id]
        @university.website = params[:university][:website]
        @university.info = params[:university][:info]
        @university.department_ids = params[:university][:department_ids]
#        @university.from_date = params[:university][:from_date]
#        @university.to_date = params[:university][:to_date]
#        params[:university][:from_date].inspect
#        params[:university][:to_date].inspect

        if @university.save
            flash[:success] = "Successfully created a new university"
            redirect_to root_url
        else
            render 'new'
        end
    end

    def edit
        @university = University.find(params[:id])
        @durations = Duration.where("university_id=?", @university.id)
    end

    def update
        @university = University.find(params[:id])

        @university.department_ids = params[:university][:department_ids]
        if @university.update!(university_params)
            flash[:success] = "Successfully updated the university information"
            redirect_to root_url
        else
            render 'edit'
        end
    end

    def archive
        @university = University.find(params[:id])
        if @university.update!(archived: 'true')
            flash[:success] = "Successfully archived the university."
            respond_to do |format|
                format.html {redirect_to @university}
                format.js
            end
        else
            flash[:error] = "Sorry, there was something wrong with the archive process. Please try again later or call Dharani @9043814168. Have fun."
        end
    end

    def unarchive
        @university = University.find(params[:id])
        if @university.update!(archived: 'false')
            flash[:success] = "Successfully unarchived the university."
            respond_to do |format|
                format.html {redirect_to @university}
                format.js
            end
        else
            flash[:error] = "Sorry, there was something wrong with the unarchive process. Please try again later or call Dharani @9043814168. Have fun."
        end
    end

    def search
        @universities = []
        @univ_name = University.search(params[:search], 'name')
        @universities = @universities + @univ_name

        @univ_desc = University.search(params[:search], 'info')
        @universities = @universities + @univ_desc
    end


    private

    def university_params
        params.require(:university).permit(:name, :country_id, :website, :info, :department_ids)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_version
    "3.3.5"
  end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/durations_helper.rb
module DurationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/countries/universities.html.erb
<% content_for :title do%>
    <%= @country.name%>
<% end %>


<div class="university_list">
    <% @universities.each do |university| %>
        <%= render university %>
<% end %>
</div>

app/views/departments/show.html.erb
<% content_for :title do%>
    <%= @department.name %>
<% end %>

<% @universities.each do |university| %>
    <%= render university %>
    <div class="margin_div">
    </div>
<% end %>

app/views/durations/_duration.html.erb
<div class="duration_div">
    <div>This duration is from <%= "#{duration.from_time}" %> till <%= "#{duration.to_date}" %></div>
</div>

app/views/durations/_new_form.html.erb
<div class="duration_form">
    <%= form_for(:duration, url: university_durations_path, remote: true, method: 'post', html: {class: 'form-horizontal'}) do |f| %>

        <%= f.label :duration_from %><br>
    <%= f.date_field :from, class: "form-control" %><br><br>

    <%= f.label :duration_to %><br>
    <%= f.date_field :to, class: "form-control" %><br><br>

    <%= f.label :application_deadline %><br>
    <%= f.date_field :deadline, class: "form-control" %><br><br>

    <%= hidden_field_tag(:university_id, "#{params[:university_id]}")%>

    <%= f.submit "Confirm Duration", class: "btn btn-primary" %><br><br>
<% end %>
</div>

app/views/durations/create.js.erb
(".durations_div").append("<%= escape_javascript(render partial: 'durations/duration', locals:{ duration: @duration, university: @university }) %>")

app/views/durations/new.js.erb
$(".new_duration_div").append("<%= escape_javascript(render partial: 'durations/new_form') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<title>International portal | <%= yield :title %></title>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/<%=bootstrap_version %>/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>

<body>
<%= render "shared/navbar"%>

<div class="main container-fluid">

        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

    <div class="main-sub container-fluid">

        <%= yield %>

    </div>

</div>

</body>

</html>

app/views/shared/_landing.html.erb
<div class="container-fluid landing_div">
    <div class="row landing_carousel" style="height:20em">
        <div class="col-md-12">
            <div class="row text-center" style="margin-top:6em">
                <div class="input-group col-md-4 col-md-offset-4">
                    <%= form_tag search_path, method: 'get' do %>
                    <%= text_field_tag :search, params[:search], placeholder:"Search", class:"form-control search_box"%>
                <%end%>
                    <span class="input-group-addon" id="search-icon"><i class="glyphicon glyphicon-search"></i></span>
                </div>
            </div>
        </div>
    </div>
    <div class="container country_filter_div">
        <div class="row countries_container">
            <div class="col-md-12">
                <div class="row text-center country_title_div">
                    <span style='vertical-align:center;'><b class='navbar-brand'>Countries</b></span>
                </div>
                <div id="countries" class="row countries">
                    <% @countries = Country.all %>
                    <% @countries.each do |country| %>
                            <%= link_to(universities_country_path(id: country.id)) do %>
                        <div class="col-md-2 country transparency" style='background-image: url(http://www.geonames.org/flags/x/<%= country.geocode.downcase %>.gif)'>
                                <div class="row center text country_div">
                                    <p class="country_name"><%= country.name %></p>
                                </div>
                        </div>
                            <% end %>
                    <% end %>
                </div>

                <% if false %> 
                    <div class="row text-center">
                        <h1>Departments</h1>
                    </div>
                    <div class="row departments">
                        <% @depts = Department.all %>
                        <% @depts.each do |dept|%>
                            <div class="col-md-1 country">
                                <div class="row center text">
                                    <%= dept.name %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class=" navbar_container container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to(root_path) do %>
                <b class="navbar-brand">International Portal</b>
        <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggdivng -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
            </form>
--!>
            <ul class="nav navbar-nav navbar-right">
            <li class="navbar_link"><%= link_to "Downloads", downloads_path %></li>
            <li class="navbar_link"><%= link_to "FAQs", faq_path %></li>
            <% if current_user.try(:admin?)%>
                <li class="navbar_link"><%= link_to "Add new University", new_university_path %></li>
            <% end %>
                <% if user_signed_in? %>
                    <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                </ul>
                </li>
            <% else %>
                <!---<li class="navbar_link"><%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="navbar_link"><%= link_to "Sign In", new_user_session_path %></li>--!>
            <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
    <%= form_tag root_path, method: 'get' do%>
        <div class="search_dropdown">Keyword Search: <br><br>
            <%= text_field_tag :search, params[:search], placeholder:"College, Dept., etc.", class:"form-control search_box" %><br>
        <label><%= check_box_tag 'name',  true, class: 'check_box' %> Name</label>&nbsp
        <label><%= check_box_tag 'description', true, class: 'check_box' %> Description</label>
        <br>
        <%= submit_tag "Search", class:"right btn btn-xs btn-primary" %>
    </div>
<% end %>
    <br>
    Filter by:<br>
</div>

app/views/static_pages/downloads.html.erb
<% content_for :title do%>
    Downloads Page
<% end %>

<div>
    Letter of Approval : <%= link_to "Letter of Approval", "/data/loa" %>
    <br>
    <br>
    <br>
    Outgoing Procedure : <%= link_to "Outgoing Procedures", "/data/op" %>
</div>

app/views/static_pages/faq.html.erb
<% content_for :title do%>
    FAQs Page
<% end %>

app/views/universities/_university.html.erb
<div class="university_div <%=university.id%>"> 

<div class="university_name">
<%= link_to university.name.capitalize, university_path(id: university.id) %>
</div>

<div>
<%= Country.find(university.country_id).name %>
</div>
<br>

<div class="university_info">
<%= raw university.info %>
</div>
<br>

<div class="departments_container"><% @departments = University.includes(:departments).find(university.id).departments %>
<% @departments.each do |department| %>
<%= link_to department.name.capitalize, department_path(id: department.id) %>
<% end %>
</div>
<% if current_user.try(:admin?)%>
<div class="extras_container btn-group">
<%= button_to "Edit", edit_university_path(id: university.id), method: :get, class: "btn btn-primary" %>
<% if university.archived %>
<%= button_to "UnArchive", unarchive_university_path(id: university.id), method: :get, remote: true, class: "btn btn-warning unarchive_button" %>
<% else %>
<%= button_to "Archive", archive_university_path(id: university.id), method: :get, remote: true, class: "btn btn-warning archive_button" %>
<% end %>
<%= button_to "Delete", university, class: "btn btn-danger",  method: :delete, data: {confirm: "Are you sure you want to delete this university?"}, remote: true  %>
</div>
<% end %>
<br>

</div>

app/views/universities/archive.js.erb
$('.university_div.<%=@university.id%>').remove()

app/views/universities/edit.html.erb
<%= content_for :title do %>
    Edit University
<% end %>

<div class="new_post_form">
    <br>
    <h1 class="form_heading">Edit University</h1></br></br>

    <div class="form_container">
        <div class="row">
            <div class="span6 offset3">
                <%= form_for(:university, url: {action: "update", id: @university.id}, method: "put", :html => { :class => "form-horizontal"}) do |f| %>

                    <%= f.label :university_name%><br>
                <%= f.text_field :name , class:"form-control", value: @university.name %><br><br>

                <%= f.label :country%><br>
                <%= f.collection_select :country_id, Country.all, :id, :name, value: @university.country_id, class:"form-control" %><br><br><br>

                <%= f.label :website%><br>
                <%= f.text_field :website , class:"form-control", value: @university.website %><br><br>

                <%= f.label :info %><br>
                <%= f.bootsy_area :info, size: "80x12", value: @university.info, class:"form-control" %><br><br>

                <%= f.label :departments, "Departments" %><br>
                <% for dept in Department.all %>
                    <label>
                    <%= check_box_tag "university[department_ids][]", dept.id, @university.departments.include?(dept) %>
                    <span>
                        <%= dept.name.capitalize %> &nbsp
                    </span>
                </label>
            <% end %>
                <br></br>

                <div class="durations_div">
                <% @durations.each do |duration| %>
                    <%= render duration %>
                <% end %>
                </div>

                <%= link_to "Add Duration", new_university_duration_path(university_id: @university.id), remote: true, class: "btn btn-success add_duration_button"%><br><br>

                <div class="new_duration_div"></div>

                <%= f.submit "Update", class: "btn btn-large btn-primary" %>
            <% end %>

            </div>
        </div>
    </div>
</div>

app/views/universities/index.html.erb
<% content_for :title do%>
    Home
<% end %>

<%= render 'shared/landing' %>

<div class="text-center row university_list_title">
    <span style="vertical-align:center;"><b class="navbar-brand">Universities</b></span>
</div>

<div class="university_list">
    <% @universities.each do |university| %>
        <%= render university %>
        <div class="margin_div">
        </div>
    <% end %>
</div>

app/views/universities/new.html.erb
<%= content_for :title do %>
    New University
<% end %>

<div class="new_post_form">
    <br>
    <h1 class="form_heading">Add New University</h1></br></br>

    <div class="form_container">
        <div class="row">
            <div class="span6 offset3">
                <%= form_for(:university, url: universities_path, method: 'post' , :html => { :class => "form-horizontal"}) do |f| %>

                    <%= f.label :university_name%><br>
                <%= f.text_field :name , class:"form-control", placeholder:"Name" %><br><br>

                <%= f.label :country%><br>
                <%= f.collection_select :country_id, Country.all, :id, :name, class:"form-control" %><br><br><br>

                <%= f.label :website%><br>
                <%= f.text_field :website , class:"form-control", placeholder:"Website" %><br><br>

                <%= f.label :info %><br>
                <%= f.bootsy_area :info, size: "80x12", class:"form-control" %><br><br>

                <%= f.label :departments %><br>
                <% for dept in Department.all %>
                    <label>
                    <%= check_box_tag "university[department_ids][]", dept.id, @university.departments.include?(dept) %>
                    <span>
                        <%= dept.name.capitalize %> &nbsp
                    </span>
                </label>
            <% end %>
                <br><br>

                <div class="new_duration_div">
                    Please add durations for each university later. Thank you.
                </div>
                <br><br>

                <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
            <% end %>

            </div>
        </div>
    </div>
</div>

app/views/universities/search.html.erb
<% content_for :title do%>
    Search Page
<% end %>

<% @universities.each do |university| %>
    <%= render university %>
    <div class="margin_div">
    </div>
<% end %>

app/views/universities/show.html.erb
<% content_for :title do%>
    <%= @university.name %>
<% end %>

<%= render @university %>

app/views/universities/unarchive.js.erb
$('.university_div.<%=@university.id%>').remove()